name: usmhub_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  icalendar_parser: ^2.1.0
  firebase_messaging: ^15.1.3
  url_launcher: ^6.3.0
  table_calendar: ^3.1.2
  dropdown_search: ^6.0.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  http: ^1.2.2
  intl: ^0.19.0
  syncfusion_flutter_calendar: ^27.1.52
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1

  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/calendars/
    - assets/images/